### ISSUE TITLE
JetEngine - Posts Meta Field Type (Improvements, Bugfix)

### ISSUE THREAD

**Issue by valmirselmani** [CrocoBlock/suggestions#5290]
I would like to customize the posts meta field type to show only certain posts. Right now you can only restrict it by custom post types. A way to sort and customize the formatting of the selected posts would also be much appreciated.

**Feature Requests**
- [ ] Add the possibility to restrict the selectable posts, e.g. by setting WP_Query arguments. 
**Example:** https://docs.metabox.io/fields/post/
_In Metabox you have more granular control over what is displayed in the meta field_
```php
[
    'name'        => 'Select a page',
    'id'          => 'page',
    'type'        => 'post',
    'post_type'   => 'page',
    'field_type'  => 'select_advanced',
    'placeholder' => 'Select a page',
    'query_args'  => [
        'post_status'    => 'publish',
        'posts_per_page' => - 1,
    ],
],
```
**Possible Solution:** customize cx_search_posts, e.g. add filters
- [ ] Add the possibility to sort the selected posts, e.g. to use them as input for listings and sort them by preserve order. At the moment you have to remove and add them again, but a bug prevents you from adding them right back again. (see below).
- [ ] Add the possibility to change the formatting, e.g. add CPT suffix if you are searching for multiple CPTs, posts can be indistinguishable because they have the same post title
**Example:** https://docs.metabox.io/fields/post/
_Metabox uses filters to customize the output of the post meta field_
```php
function my_field_filter( $label, $field, $post ) {
    return $post->post_title . ' - ' . $post->post_status;
}
add_filter( 'rwmb_my_field_choice_label', 'my_field_filter', 10, 3 );
```
**Possible Solution:** customize cx_search_posts, e.g. add filters

**Bug Fixes**
- [ ] When you select a post and remove it again, you cannot add it again. You have to save it first, reload the page and then you can add that particular post again. The removed post is still selected, but hidden, maybe that's why it can't be added again.

The functionality of the meta fields is still not on the level of other plugins. You should take inspiration from ACF or Metabox. That would significantly improve the product and get more users to use your plugins. I am already a happy lifetime user of Crocoblock plugins, but I would be even happier if the meta fields functionality would be improved.
